export const oxfordLibraries = [
  "Alexander Library of Ornithology",
  "All Souls College Library",
  "Art, Archaeology and Ancient World Library",
  "Balfour Library (Pitt Rivers Museum)",
  "Balliol College Library",
  "Bodleian Education Library",
  "Bodleian History Faculty Library",
  "Bodleian Japanese Library",
  "Bodleian KB Chen China Centre Library",
  "Bodleian Latin American Centre Library",
  "Bodleian Law Library",
  "Bodleian Library - Old Library",
  "Bodleian Library - Radcliffe Camera",
  "Bodleian Library - Weston Library",
  "Bodleian Music Faculty Library",
  "Bodleian Oriental Institute Library",
  "Bodleian Social Science Library",
  "Brasenose College Library",
  "Cairns Library",
  "Campion Hall Library",
  "Centre for Teaching and Learning Information",
  "Chantry Library",
  "Christ Church Library",
  "Computer Science Library",
  "Continuing Education Library",
  "Corpus Christi College Library",
  "Duke Humfrey's Library",
  "Earth Sciences Library",
  "English Faculty Library",
  "Exeter College Library",
  "Gladstone Link (Glink)",
  "Green Templeton College Library",
  "Harris Manchester College Library",
  "Health Care Libraries - Knowledge Centre",
  "Hertford College Library",
  "History of Science Museum Library",
  "Institute of Archaeology Library",
  "Instituto Camoes Library",
  "Jesus College Library",
  "Keble College Library",
  "Kellogg College Library",
  "Lady Margaret Hall Library",
  "Language Centre Library",
  "Leopold Muller Memorial Library (Hebrew & Jewish Studies)",
  "Linacre College Library",
  "Lincoln College Library",
  "Magdalen College Library",
  "Maison Française Library",
  "Mansfield College Library",
  "Materials Library",
  "Mathematical Institute Library",
  "Merton College Library",
  "Middle East Centre Library",
  "Museum of Natural History Library",
  "Nizami Ganjavi Library",
  "New College Library",
  "Nuffield College Library",
  "Oriel College Library",
  "Oxford Centre for Islamic Studies Library",
  "Oxford Centre for Mission Studies Library",
  "Oxford Internet Institute Library",
  "Oxford Union Society Library",
  "Oxfordshire History Centre Library",
  "Pauling Centre for Human Sciences Library",
  "Pembroke College Library",
  "Philosophy and Theology Faculties Library",
  "Physiology Library",
  "Pitt Rivers Museum Library",
  "Pusey House Library",
  "Queen's College Library",
  "Radcliffe Science Library",
  "Regent's Park College Library",
  "Research Laboratory for Archaeology Library",
  "Rewley House Continuing Education Library",
  "Ruskin School of Drawing and Fine Art Library",
  "Russian and Eurasian Studies Centre Library",
  "Sainsbury Library",
  "Sherardian Library of Plant Taxonomy",
  "Sir William Dunn School of Pathology Library",
  "Somerville College Library",
  "St Anne's College Library",
  "St Antony's College Library",
  "St Benet's Hall Library",
  "St Catherine's College Library",
  "St Cross College Library",
  "St Edmund Hall Library",
  "St Hilda's College Library",
  "St Hugh's College Library",
  "St John's College Library",
  "St Peter's College Library",
  "Statistics Library",
  "Taylor Institution Library",
  "Trinity College Library",
  "Tylor Library",
  "University College Library",
  "Vere Harmsworth Library",
  "Wadham College Library",
  "Wellcome Unit for the History of Medicine Library",
  "Wolfson College Library",
  "Worcester College Library",
  "Wycliffe Hall Library"
].sort(); 